### ISSUE TITLE
[Bug] Multiline license support?

### ISSUE THREAD

**Issue by JoshLind** [chasinglogic/licensure#25]
Hi,

I am trying to use the tool to provide a very simple license check on rust files, but, for some reason, I cannot get the tool to produce a license over multiple lines. For example, this is my `.licensure.yml` file:

```
change_in_place: false

licenses:
  - files: .*\.rs
    ident: Apache-2.0
    authors:
      - name: TestName
    template: |
      Copyright (c) [name of author]
      SPDX-License-Identifier: [ident]

comments:
    - extension: rs
      commenter:
        type: line
        comment_char: "//"
        trailing_lines: 1

excludes:
    - \.gitignore
```

Instead of getting:
```
// Copyright (c) TestName
// SPDX-License-Identifier: Apache-2.0 
```

the tool returns:
```
// Copyright (c) TestName SPDX-License-Identifier: Apache-2.0 
```

Note: I am running the `licensure --check` command which is producing a mismatch because it expects a license on a single line. Is there anything I'm missing here? Thanks for your help 😄
